"""Assemble the static, phone-first Tessera Workshop.

SPDX-License-Identifier: 0BSD

The site contains no second source of truth.  Every displayed asset, brief,
example and downloadable pack is generated from the repository's current
catalog and handoff code.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tessera.brief import build_brief, render_text  # noqa: E402
from tessera.catalog import load_catalog  # noqa: E402
from tessera.handoff import (  # noqa: E402
    build_manifest, render_start_here, write_handoff_pack,
)
from tessera.validate import Collector, validate_asset, validate_layout  # noqa: E402

MARKER = ".tessera-workshop-build"
EXAMPLES = (
    ("workshop_shell", "Workshop shell", "Single-storey shell with a proven entrance route."),
    ("safehouse", "Safe house", "A compact defensive shell assembled from metadata."),
    ("safehouse_two_storey", "Two-storey safe house", "Stairs and reachability across two levels."),
    ("interior_rooms", "Interior rooms", "Perimeter-to-partition junctions and enterable rooms."),
)


def prepare_output(out: Path):
    resolved = out.resolve()
    forbidden = {ROOT.resolve(), ROOT.parent.resolve(), Path.home().resolve(),
                 Path(resolved.anchor)}
    if resolved in forbidden:
        raise ValueError("Workshop output must be a dedicated directory.")
    if out.exists():
        marker = out / MARKER
        if not marker.is_file():
            raise ValueError("Refusing to replace unmarked directory %s" % out)
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text("generated by tools/build_workshop.py\n", encoding="utf-8")


def copy_tree(source: Path, target: Path):
    for path in sorted(item for item in source.rglob("*") if item.is_file()):
        relative = path.relative_to(source)
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, destination)


def build(out: Path):
    prepare_output(out)
    copy_tree(ROOT / "workshop", out)
    (out / ".nojekyll").write_text("", encoding="utf-8")

    data = out / "data"
    examples_out = data / "examples"
    downloads = out / "downloads"
    library = out / "lib"
    for directory in (data, examples_out, downloads, library):
        directory.mkdir(parents=True, exist_ok=True)

    catalog = load_catalog(ROOT / "build" / "catalog.json")
    brief = build_brief(catalog)
    (data / "catalog.json").write_text(
        json.dumps(catalog, separators=(",", ":")), encoding="utf-8")
    (data / "brief.json").write_text(
        json.dumps(brief, separators=(",", ":")), encoding="utf-8")
    (data / "brief.txt").write_text(render_text(brief), encoding="utf-8")
    shutil.copy2(
        ROOT / "adapters" / "three" / "src" / "tessera-core.mjs",
        library / "tessera-core.mjs")

    examples = []
    example_layouts = []
    for slug, name, description in EXAMPLES:
        source = ROOT / "examples" / slug / "layout.json"
        layout = json.loads(source.read_text(encoding="utf-8"))
        filename = "%s.json" % slug
        shutil.copy2(source, examples_out / filename)
        examples.append({
            "id": slug,
            "file": filename,
            "name": name,
            "description": description,
            "instances": layout.get("instance_count", len(layout.get("instances", []))),
        })
        example_layouts.append(layout)

    asset_checks = Collector()
    for asset in catalog["assets"]:
        validate_asset(asset, asset_checks)
    layout_checks = validate_layout(example_layouts[0], catalog)
    full_check_count = len(set(asset_checks.checks_run + layout_checks.checks_run))

    site_manifest = {
        "schema": "tessera.workshop/1",
        "catalog": {
            "kit": "%s@%s" % (catalog["kit"]["id"], catalog["kit"]["version"]),
            "fingerprint": catalog["fingerprint"],
            "assets": catalog["asset_count"],
        },
        "browser_validation": {
            "checks": 5,
            "scope": [
                "known assets", "support and grounding", "intersections",
                "traversable aperture blockage",
            ],
            "claim": "runtime subset",
        },
        "full_validation": {
            "checks": full_check_count,
            "delivery": "downloads/tessera-sandbox.zip",
        },
        "examples": examples,
        "privacy": {
            "login": False,
            "telemetry": False,
            "uploads_leave_device": False,
        },
    }
    (data / "workshop.json").write_text(
        json.dumps(site_manifest, indent=2), encoding="utf-8")

    chat_manifest = build_manifest(
        catalog, "chat", brief,
        "Build the requested world and return a fingerprinted Tessera layout.")
    chat_start = render_start_here(chat_manifest, render_text(brief))
    (downloads / "tessera-chat.md").write_text(chat_start, encoding="utf-8")
    write_handoff_pack(
        catalog=catalog, target="chat",
        out_path=downloads / "tessera-chat.zip", repo_root=ROOT,
        prompt="Build the requested world and return a fingerprinted Tessera layout.")
    write_handoff_pack(
        catalog=catalog, target="sandbox",
        out_path=downloads / "tessera-sandbox.zip", repo_root=ROOT,
        prompt=("Build or continue the requested world. Run full validation and "
                "apply only validator-supplied corrections."))

    return {
        "out": str(out),
        "assets": catalog["asset_count"],
        "examples": len(examples),
        "fingerprint": catalog["fingerprint"],
        "sandbox_bytes": (downloads / "tessera-sandbox.zip").stat().st_size,
    }


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="dist")
    args = parser.parse_args(argv)
    result = build((ROOT / args.out).resolve())
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
