"""Build the machine-readable provenance manifest.

SPDX-License-Identifier: 0BSD

"The repository is CC0" is not an auditable statement. "This file has this
hash, was produced by this function at this version, from these inputs, and
nothing external was read" is. This script produces the second kind.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from tessera.measure import utcnow  # noqa: E402

SKIP_DIRS = {".git", "__pycache__", "node_modules", ".pytest_cache", "fixtures"}


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def git_commit():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True,
            stderr=subprocess.DEVNULL).strip()
    except Exception:
        return None


def main():
    catalog_path = os.path.join(ROOT, "build", "catalog.json")
    with open(catalog_path, encoding="utf-8") as fh:
        catalog = json.load(fh)

    entries = []
    for asset in catalog["assets"]:
        files = []
        for role, rel in asset["files"].items():
            path = os.path.join(ROOT, "build", rel)
            if os.path.exists(path):
                files.append({"role": role, "path": "build/" + rel,
                              "sha256": sha256(path), "bytes": os.path.getsize(path)})
        entries.append({
            "asset": asset["id"],
            "origin": asset["provenance"]["origin"],
            "generator": asset["provenance"]["generator"],
            "generator_version": asset["provenance"]["generator_version"],
            "authored_by": asset["provenance"]["authored_by"],
            "source_inputs": asset["provenance"]["source_inputs"],
            "third_party_review": asset["provenance"]["third_party_review"],
            "geometry_sha256": asset["geometry"]["sha256"],
            "license": asset["license"],
            "files": files,
        })

    generators = []
    for folder in ("src/tessera", "kits/shell_v1", "tools"):
        base = os.path.join(ROOT, folder)
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for name in sorted(filenames):
                if name.endswith(".py"):
                    p = os.path.join(dirpath, name)
                    generators.append({
                        "path": os.path.relpath(p, ROOT).replace(os.sep, "/"),
                        "sha256": sha256(p),
                    })

    manifest = {
        "schema": "tessera.provenance/1",
        "generated_utc": utcnow(),
        "git_commit": git_commit(),
        "declaration": (
            "Every asset listed here was generated from scratch by the named "
            "function in this repository. No third-party mesh, texture, model, "
            "scan, photograph or asset library is read at any point in the "
            "generation pipeline. source_inputs is empty for every entry, and "
            "the validator fails any asset for which it is not."
        ),
        "license": {
            "code_spdx": "0BSD",
            "assets_spdx": "CC0-1.0",
            "attribution_required": False,
            "commercial_use": True,
            "redistribution": True,
        },
        "third_party_runtime_dependencies": [],
        "third_party_build_dependencies": [],
        "third_party_test_dependencies": [
            {"name": "pytest", "spdx": "MIT", "used_for": "running the test suite",
             "affects_output": False},
            {"name": "jsonschema", "spdx": "MIT",
             "used_for": "checking the shipped schemas describe the shipped data",
             "affects_output": False},
            {"name": "trimesh", "spdx": "MIT",
             "used_for": "independent verification that exported GLB files are watertight",
             "affects_output": False},
        ],
        "conceptual_lineage": [
            {"source": "JaronKBragg7337/asset-pack-ue-threejs-blender-unity",
             "owner": "Jaron K Bragg", "license": "CC0-1.0",
             "carried_forward": [
                 "single-source-of-truth kit config with a validate() that refuses "
                 "impossible parameter combinations",
                 "explicit per-category pivot conventions",
                 "everything generated by script, no hand-placed vertices",
                 "world-space consistent UV0 texel density and a packed UV1",
                 "an assembled example scene as ground truth",
             ],
             "rejected": [
                 "Blender as a hard pipeline dependency",
                 "boolean-modifier CSG",
                 "committed binary build outputs",
                 "unauthored collision",
             ],
             "code_copied": "none - every line was rewritten against the new contract"},
            {"source": "JaronKBragg7337/World-Printer-Lab-For-3D-Worlds",
             "owner": "Jaron K Bragg", "license": "MIT",
             "carried_forward": [
                 "connectors as position plus normal plus kind",
                 "mating gated on opposed normals rather than proximity alone",
                 "scale classes as standards that refuse to mate across",
                 "fail-closed admission with provenance and rejection reasons",
                 "measured grounded bounds as the basis for derived metadata",
             ],
             "rejected": [
                 "Y-up/Z-up ambiguity in the dims ordering",
                 "magic tolerance constants buried in snapping code",
                 "Supabase coupling",
                 "legacy version sprawl",
                 "third-party asset sourcing plan",
             ],
             "code_copied": "none - concepts only, reimplemented in Python and JS"},
        ],
        "asset_count": len(entries),
        "assets": entries,
        "generators": generators,
    }

    out = os.path.join(ROOT, "provenance", "manifest.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(manifest, fh, indent=2)
    print("wrote %s (%d assets, %d generator files)"
          % (out, len(entries), len(generators)))


if __name__ == "__main__":
    main()
