"""Verify the Unreal adapter against a real Unreal Engine.

SPDX-License-Identifier: 0BSD

    UnrealEditor-Cmd.exe <Project>.uproject ^
        -ExecutePythonScript="tools/verify_unreal.py" ^
        -unattended -nopause -nosplash -NullRHI

Checks what comes out the other side, not that the script ran:

* every asset imports and its bounds match the contract, in Unreal's units and
  handedness, to within a millimetre
* the collision Unreal generated by itself is gone, replaced by the contract's
  hulls, one for one
* a doorway's collision is genuinely void where its aperture is -- with a note
  recording what Unreal's own auto-collision would have done instead
* a whole layout spawns at the transforms the layout specifies

Writes build/unreal-verify-report.json and logs VERIFY lines for the harness.
"""
import json
import os
import sys

import unreal

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "adapters", "unreal"))
TOLERANCE_CM = 0.1

import tessera_unreal as tu  # noqa: E402

checks = []


def check(name, ok, detail=""):
    checks.append({"name": name, "ok": bool(ok), "detail": detail})
    unreal.log("VERIFY %-4s %-48s %s" % ("ok" if ok else "FAIL", name, detail))
    return ok


def bounds_of(mesh):
    b = mesh.get_bounding_box()
    return ([b.min.x, b.min.y, b.min.z], [b.max.x, b.max.y, b.max.z])


def expected_bounds(record):
    lo = record["dimensions"]["bounds"]["min"]
    hi = record["dimensions"]["bounds"]["max"]
    a = tu.to_unreal_location(lo)
    c = tu.to_unreal_location(hi)
    return ([min(a[i], c[i]) for i in range(3)], [max(a[i], c[i]) for i in range(3)])


def main():
    with open(os.path.join(ROOT, "build", "catalog.json"), encoding="utf-8") as fh:
        catalog = json.load(fh)
    base = os.path.join(ROOT, "build")
    unreal.log("VERIFY engine %s" % unreal.SystemLibrary.get_engine_version())

    meshes = {}
    auto_hulls = {}
    for record in catalog["assets"]:
        short = record["id"].split("/")[-1]
        try:
            mesh = tu.import_asset(record, base, "/Game/TesseraVerify")
        except Exception as exc:
            check("%s imports" % short, False, str(exc)[:120])
            continue
        check("%s imports" % short, True)

        # what did Unreal decide to do on its own, before we intervene?
        body = mesh.get_editor_property("body_setup")
        agg = body.get_editor_property("agg_geom") if body else None
        auto_hulls[short] = (len(agg.get_editor_property("convex_elems")) if agg else 0)

        lo, hi = bounds_of(mesh)
        want_lo, want_hi = expected_bounds(record)
        worst = max(max(abs(lo[i] - want_lo[i]), abs(hi[i] - want_hi[i]))
                    for i in range(3))
        check("%s bounds match the contract" % short, worst <= TOLERANCE_CM,
              "worst axis error %.4f cm" % worst)

        n = tu.apply_collision(mesh, record)
        check("%s collision rebuilt from the contract" % short,
              n == record["collision"]["hull_count"],
              "%d of %d hulls" % (n, record["collision"]["hull_count"]))

        body = mesh.get_editor_property("body_setup")
        agg = body.get_editor_property("agg_geom")
        boxes = agg.get_editor_property("box_elems")
        convex = agg.get_editor_property("convex_elems")
        check("%s auto-generated collision removed" % short, len(convex) == 0,
              "%d convex hull(s) left" % len(convex))
        check("%s box collision persisted" % short, len(boxes) == n,
              "%d box(es) stored" % len(boxes))
        meshes[record["id"]] = mesh

    # ------------------------------------------------- the doorway is void
    doorway = next(a for a in catalog["assets"] if a["id"].endswith("wall.doorway.4m"))
    mesh = meshes.get(doorway["id"])
    if mesh:
        ap = doorway["apertures"][0]
        alo, ahi = tu.to_unreal_location(ap["bounds"]["min"]), tu.to_unreal_location(ap["bounds"]["max"])
        lo = [min(alo[i], ahi[i]) for i in range(3)]
        hi = [max(alo[i], ahi[i]) for i in range(3)]
        agg = mesh.get_editor_property("body_setup").get_editor_property("agg_geom")
        pad = 1.0
        intruders = 0
        for b in agg.get_editor_property("box_elems"):
            c = b.get_editor_property("center")
            half = [b.get_editor_property("x") / 2, b.get_editor_property("y") / 2,
                    b.get_editor_property("z") / 2]
            cc = [c.x, c.y, c.z]
            if all(cc[i] - half[i] < hi[i] - pad and cc[i] + half[i] > lo[i] + pad
                   for i in range(3)):
                intruders += 1
        check("doorway collision leaves the aperture void", intruders == 0,
              "%d hull(s) inside the opening" % intruders)
        check("Unreal would have sealed it without us",
              auto_hulls.get("wall.doorway.4m", 0) > 0,
              "auto-generated %d convex hull(s) on import"
              % auto_hulls.get("wall.doorway.4m", 0))

    # ------------------------------------------------------ spawn a layout
    layout_path = os.path.join(ROOT, "examples", "safehouse_two_storey", "layout.json")
    with open(layout_path, encoding="utf-8") as fh:
        layout = json.load(fh)
    actors = tu.spawn_layout(layout, meshes)
    check("layout spawns every instance", len(actors) == layout["instance_count"],
          "%d of %d" % (len(actors), layout["instance_count"]))

    by_id = {i["id"]: i for i in layout["instances"]}
    worst, worst_name = 0.0, ""
    for actor in actors:
        spec = by_id.get(actor.get_actor_label())
        if not spec:
            continue
        want = tu.to_unreal_location(spec["position"])
        got = actor.get_actor_location()
        err = max(abs(got.x - want[0]), abs(got.y - want[1]), abs(got.z - want[2]))
        if err > worst:
            worst, worst_name = err, actor.get_actor_label()
    check("actors land at the layout's transforms", worst <= TOLERANCE_CM,
          "worst %.4f cm (%s)" % (worst, worst_name))

    failed = [c for c in checks if not c["ok"]]
    report = {
        "engine": unreal.SystemLibrary.get_engine_version(),
        "fingerprint": catalog.get("fingerprint"),
        "checks": len(checks),
        "failed": len(failed),
        "auto_generated_hulls_before_replacement": auto_hulls,
        "results": checks,
    }
    out = os.path.join(ROOT, "build", "unreal-verify-report.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2)

    unreal.log("VERIFY TOTAL %d checks, %d failed" % (len(checks), len(failed)))
    if failed:
        for c in failed:
            unreal.log_error("VERIFY FAILED %s: %s" % (c["name"], c["detail"]))
    else:
        unreal.log("VERIFY Unreal adapter VERIFIED")


main()
